# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '* * */1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: setup python  
        uses: actions/setup-python@v2
      - name: setup packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            requests
            bs4
            beautifulsoup4 
        
      # Runs a single command using the runners shell
      - name: Run scraper
        run: bash commit.sh
        working-directory: ./anuscrape
      
      - name: Update date
        run: python update_date.py
        working-directory: ./anuscrape
